pub const GET_MESSAGE_BETWEEN_USER_STMT: &str = "
SELECT * FROM PUBLIC.MESSAGE
    WHERE (RECEIVER_ID = $1 AND SENDER_ID = $2)
    OR (RECEIVER_ID = $2 AND SENDER_ID = $1)
ORDER BY SENT_AT ASC;
";
pub const UPDATE_MESSAGE_READ_STMT: &str = "
UPDATE PUBLIC.MESSAGE
    SET READ = TRUE
WHERE RECEIVER_ID = $1
    AND SENDER_ID = $2
";
pub const GET_RECENT_MESSAGE_STMT: &str = "
SELECT
    UNREAD_MESSAGE_CONTENT.ID,
    CASE WHEN SENDER_ID = $1 THEN RECEIVER_ID ELSE SENDER_ID END AS CONTACT_ID,
    SENT_AT,
    LAST_MESSAGE,
    CASE WHEN RECEIVER_ID != $1 THEN 0 ELSE UNREAD_COUNT END,
    PUBLIC.USER.USERNAME,
    DELETED
FROM PUBLIC.UNREAD_MESSAGE_CONTENT
    JOIN PUBLIC.USER ON 
        CASE WHEN LEAST(RECEIVER_ID, SENDER_ID) = $1 THEN
            GREATEST(RECEIVER_ID, SENDER_ID) = PUBLIC.USER.ID
        ELSE
            LEAST(RECEIVER_ID, SENDER_ID) = PUBLIC.USER.ID
        END
WHERE $1 IN (SENDER_ID, RECEIVER_ID)
ORDER BY SENT_AT DESC
;
";
pub const CREATE_MESSAGE_STMT: &str = "
    INSERT INTO PUBLIC.MESSAGE (SENDER_ID, RECEIVER_ID, CONTENT)
    VALUES ($1, $2, $3) RETURNING *;
";
pub const DELETE_MESSAGE_STMT: &str = "
UPDATE PUBLIC.MESSAGE
    SET DELETED = TRUE
WHERE ID = $1;
";
pub const FIND_MESSAGE_BY_ID_STMT: &str = "
    SELECT * FROM PUBLIC.MESSAGE
        WHERE ID = $1
    LIMIT 1
";
pub const EDIT_MESSAGE_BY_ID_STMT: &str = "
UPDATE PUBLIC.MESSAGE
    SET CONTENT = $2, EDITED = TRUE
WHERE ID = $1 RETURNING *
";
