pub const GET_MESSAGE_BETWEEN_USER_STMT: &str = "
SELECT * FROM PUBLIC.MESSAGE
    WHERE (RECEIVER_ID = $1 AND SENDER_ID = $2)
    OR (RECEIVER_ID = $2 AND SENDER_ID = $1)
ORDER BY SENT_AT ASC;
";
pub const UPDATE_MESSAGE_READ_STMT: &str = "
UPDATE PUBLIC.MESSAGE
    SET READ = TRUE
WHERE RECEIVER_ID = $1
    AND SENDER_ID = $2;   
";
pub const GET_RECENT_MESSAGE_STMT: &str = "
SELECT
    UNREAD_MESSAGE_CONTENT.ID,
    CASE WHEN SENDER_ID = $1 THEN RECEIVER_ID ELSE SENDER_ID END AS CONTACT_ID,
    SENT_AT,
    LAST_MESSAGE,
    PUBLIC.USER.USERNAME
FROM PUBLIC.UNREAD_MESSAGE_CONTENT
    JOIN PUBLIC.USER ON 
        CASE WHEN LEAST(RECEIVER_ID, SENDER_ID) = $1 THEN
            GREATEST(RECEIVER_ID, SENDER_ID) = PUBLIC.USER.ID
        ELSE
            LEAST(RECEIVER_ID, SENDER_ID) = PUBLIC.USER.ID
        END
WHERE $1 IN (SENDER_ID, RECEIVER_ID)
";
pub const CREATE_MESSAGE_STMT: &str = "
    INSERT INTO PUBLIC.MESSAGE (SENDER_ID, RECEIVER_ID, CONTENT, SENT_AT)
    VALUES ($1, $2, $3, $4) RETURNING *;
";