//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::blog::Entity as Blog;
pub use super::image::Entity as Image;
pub use super::message::Entity as Message;
pub use super::user::Entity as User;
