pub const USER_PROFILE_UPSERT_STATEMENT: &str = "
    INSERT INTO PUBLIC.USER_AVATAR (USER_ID, AVATAR_IMAGE)
    VALUES ($1, $2) ON CONFLICT (USER_ID)
    DO UPDATE SET AVATAR_IMAGE = $2
";

pub const GET_USER_PROFILE: &str = "
    SELECT * FROM PUBLIC.USER_AVATAR WHERE USER_ID = $1
";