pub const CREATE_SESSION_STMT: &str = "
    INSERT INTO PUBLIC.SESSION(USER_ID, OPERATING_SYSTEM, AGENT, CREATED_AT, LAST_ACTIVE)
    VALUES ($1, $2, $3, $5, $5) RETURNING *;
";

pub const FIND_SESSION_BY_USER_ID: &str = "
    SELECT * FROM PUBLIC.SESSION WHERE USER_ID = $1;
";