SELECT * FROM PUBLIC.MESSAGE ORDER BY ID DESC LIMIT 20;

SELECT * FROM PUBLIC.GROUP_MESSAGE ORDER BY ID DESC LIMIT 20;

SELECT SENT_AT FROM PUBLIC.GROUP_MESSAGE WHERE ID = 14;


UPDATE PUBLIC.MESSAGE  SET SENT_AT = SENT_AT - interval '1 hour' * 7 WHERE ID <= 33;

