pub const FIND_USER_BY_EMAIL_STMT: &str = "SELECT * FROM PUBLIC.USER WHERE EMAIL = $1";
pub const FIND_USER_BY_ID_STMT: &str = "SELECT * FROM PUBLIC.USER WHERE ID = $1";
pub const UPDATE_USERNAME_STMT: &str = "UPDATE PUBLIC.USER SET USERNAME = $1 WHERE ID = $2";
pub const UPDATE_EMAIL_STMT: &str = "UPDATE PUBLIC.USER SET EMAIL = $1 WHERE ID = $2";
pub const UPDATE_PASSWORD_STMT: &str =
    "UPDATE PUBLIC.USER SET PASSWORD = CRYPT($1, GEN_SALT('bf', 5)) WHERE ID = $2";
pub const CREATE_USER_STMT: &str = "INSERT INTO PUBLIC.USER (USERNAME, EMAIL, PASSWORD) VALUES ($1, $1, CRYPT($2, GEN_SALT('bf', 5)))";
